In [ ]:
THIS CODE IS NOT COMPLETE YET

In [11]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pylab import rcParams
import math

In [12]:
def sigmoid(x):
    return 1/ (1 + math.e ** -x)
def sigmoid_derivative(x):
    return (sigmoid(x) * (1-sigmoid(x)))

In [13]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])
print(x)
print(y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [1]
 [1]
 [0]]


In [62]:
epochs = 5000
input_size , hidden_size , output_size = 2 , 3, 1
learning_rate = 0.1


In [66]:
W1 = np.random.uniform(size = (input_size,hidden_size))
W2 = np.random.uniform(size = (hidden_size,output_size))

In [67]:
def doComputation(W1,W2,learning_rate):
    z1 = np.dot(x,W1)
    A1 = sigmoid(z1)
    #print(A1)
    z2 = np.dot(A1,W2)
    y_hat = sigmoid(z2)
    #print(y_hat)
    E = y_hat - y
    #print(E)
    learning_rate = learning_rate*E
    return E,learning_rate

In [70]:
learning_rate = .1
for i in range(epochs):
    delta1 = E*learning_rate #1
    W2  -= np.dot(A1.T,delta1)  #2
    #print(delta1.shape)
    #print(W2.shape)
    delta2 = np.dot(delta1,W2.T) * sigmoid_derivative(A1) #3
    #print(delta2.shape)
    #print(x.T.shape)
    W1 -= np.dot(x.T,delta2)#4
    E,learning_rate = doComputation(W1,W2,learning_rate)
    print(E,end="\n\n")


[[ 0.05708127]
 [-0.04063153]
 [-0.04167495]
 [ 0.06041744]]
[[ 0.57081269]
 [-0.40631526]
 [-0.41674947]
 [ 0.60417439]]

[[0.03124851]
 [0.0177753 ]
 [0.01844097]
 [0.03450465]]
[[ 0.54743892]
 [-0.43747557]
 [-0.44249533]
 [ 0.57110414]]

[[ 0.01695748]
 [-0.00788985]
 [-0.00825711]
 [ 0.01947132]]
[[ 0.54266516]
 [-0.44386588]
 [-0.44775886]
 [ 0.56431005]]

[[0.00909554]
 [0.00356857]
 [0.0037545 ]
 [0.01081318]]
[[ 0.53637319]
 [-0.45229867]
 [-0.45469902]
 [ 0.55533869]]

[[ 0.00486269]
 [-0.00162243]
 [-0.00171441]
 [ 0.00597797]]
[[ 0.53462382]
 [-0.45464555]
 [-0.45662909]
 [ 0.55284092]]

[[0.00259136]
 [0.00074137]
 [0.0007861 ]
 [0.00329021]]
[[ 0.53290761]
 [-0.45694847]
 [-0.45852283]
 [ 0.55038944]]

[[ 0.00137945]
 [-0.00033935]
 [-0.00036095]
 [ 0.00180817]]
[[ 0.53232703]
 [-0.45772788]
 [-0.45916354]
 [ 0.54955966]]

[[0.00073366]
 [0.00015554]
 [0.00016592]
 [0.00099246]]
[[ 0.53185089]
 [-0.45836705]
 [-0.45968901]
 [ 0.54887912]]

[[ 3.90064312e-04]
 [-7.13350380

[[ 3.14364150e-139]
 [-2.84505954e-171]
 [-1.11564640e-170]
 [ 2.02235088e-132]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[1.67052050e-139]
 [1.30581715e-171]
 [5.13409769e-171]
 [1.10871255e-132]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 8.87708967e-140]
 [-5.99340153e-172]
 [-2.36266250e-171]
 [ 6.07829003e-133]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[4.71725554e-140]
 [2.75083399e-172]
 [1.08727461e-171]
 [3.33229832e-133]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 2.50673370e-140]
 [-1.26256978e-172]
 [-5.00353345e-172]
 [ 1.82686447e-133]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[1.33206984e-140]
 [5.79490602e-173]
 [2.30257809e-172]
 [1.00154112e-133]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 7.07857427e-141]
 [-2.65972910e-173]
 [-1.05962435e-172]
 [ 5.49074458e-134]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[3.7615305

 [6.96345971e-244]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 9.47715328e-257]
 [-5.01929318e-316]
 [-6.09259455e-315]
 [ 3.81757452e-244]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.03612732e-257]
 [2.30374056e-316]
 [2.80375356e-315]
 [2.09290723e-244]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 2.67618109e-257]
 [-1.05736412e-316]
 [-1.29026049e-315]
 [ 1.14739363e-244]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[1.42211361e-257]
 [4.85305911e-317]
 [5.93765499e-316]
 [6.29035115e-245]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 7.55706383e-258]
 [-2.22744309e-317]
 [-2.73245184e-316]
 [ 3.44855650e-245]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[4.01579826e-258]
 [1.02234534e-317]
 [1.25744811e-316]
 [1.89060064e-245]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 2.13398167e-258]
 [-4.69232918e-318]
 [-5.78665544e-317]
 [ 1.0364831

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+00

 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5

 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+00

 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5

 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]



 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.531

 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.

 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5.e-324]
 [-0.e+000]
 [-0.e+000]
 [ 5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[5.e-324]
 [0.e+000]
 [0.e+000]
 [5.e-324]]
[[ 0.53139663]
 [-0.45897709]
 [-0.46019041]
 [ 0.54822957]]

[[ 5